spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: postgres
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/user_db
    pool:
      enabled: true
      max-idle-time: 1m
  data:
    r2dbc:
      repositories:
        enabled: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: mail-service-route
#          uri: lb://mail-service
#          predicates:
#            - Path=/mail-service/**
#          filters:
#            -
server:
  port: ${SERVER_PORT:8762}
eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_URL:localhost:8761/eureka/}
jwt:
  secret:
    access: 5b96612a62d527b6b92541fceec46ad5126c6577a679feec8f83d36babf58016
    refresh: 5803daf0fe4c11d1cd8691969a8c2006bb9beb9478bac49dfe5c46cece7e99f4
  accessExpirationMinutes: 5
  refreshExpirationDays: 30
clients:
  mail-service:
    name: mail-service
    path:
    url:
logging:
  level:
    org.springframework.r2dbc: debug
    org.springframework.cloud.gateway: debug