spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: postgres
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/user_db
    pool:
      enabled: true
      max-idle-time: 1m
  data:
    r2dbc:
      repositories:
        enabled: true
  application:
    name: api-gateway
server:
  port: ${SERVER_PORT:8762}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG