package api.invest.dto.tinkoffinvestapi.type;

public enum InstrumentType {
    INSTRUMENT_TYPE_UNSPECIFIED,
    INSTRUMENT_TYPE_BOND,
    INSTRUMENT_TYPE_SHARE,
    INSTRUMENT_TYPE_CURRENCY,
    INSTRUMENT_TYPE_ETF,
    INSTRUMENT_TYPE_FUTURES,
    INSTRUMENT_TYPE_SP,
    INSTRUMENT_TYPE_OPTION,
    INSTRUMENT_TYPE_CLEARING_CERTIFICATE,
    INSTRUMENT_TYPE_INDEX,
    INSTRUMENT_TYPE_COMMODITY
}
